version: '2'
services: 
    postgres:
        build: 
            context: "./postgres"
            args: 
                - http_proxy
                - https_proxy
                - no_proxy
        ports: 
            - "5432:5432"
        container_name: postgres
        environment: 
            - http_proxy
            - https_proxy
            - no_proxy
        working_dir: '/usr/work'
        volumes: 
            - ./postgres_work:/usr/work
        volumes_from: 
            - db_data

    db_data:
        image: busybox
        volumes: 
            - ./db_data:/var/lib/postgresql/data
