FROM postgres:9.3
ARG http_proxy
ARG https_proxy
ARG no_proxy
ENV http_proxy=$http_proxy https_proxy=$https_proxy no_proxy=$no_proxy
RUN localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8
ENV DEBIAN_FRONTEND noninteractive
RUN apt-mark hold postgresql-$PG_MAJOR && apt-get -y update && apt-get -y install postgresql-9.3-postgis-2.3 --fix-missing
ENV LANG ja_JP.utf8
ENV POSTGRES_INITDB_ARGS "--encoding=UTF-8 --locale=ja_JP.UTF-8"
